### ISSUE TITLE
The form isn't submitted. 

### ISSUE THREAD

**Issue by Klodd65** [bmlt-enabled/bmlt-workflow#179]
I went to create a new installation of BMLT-Worflow on our website at https://na-outaouais.org/reunions/
If a member fill a new submission, nothing is happening, no add on the db table 'wpb4_bmltwf_submissions', no email sent, just a refresh, that is all.

Here is my attached config file if needed.
[backup-202309170955.zip](https://github.com/bmlt-enabled/bmlt-workflow/files/12642972/backup-202309170955.zip)

![image](https://github.com/bmlt-enabled/bmlt-workflow/assets/3509271/6a86a605-42df-43f1-bb1d-92feb18da429)

**Comment by nigel-bmlt** [comment]
Hi Claude - I'm just away due to a death in the family and will get to looking at this next week.

In the first instance I would take a look at your php error log if available - we're looking for anything that suggests more fatal errors.

Also can you confirm you are successfully able to configure the plugin. ie are you able to connect to your BMLT server, configure the service bodies and add users to them etc.

**Comment by Klodd65** [comment]
[error.log](https://github.com/bmlt-enabled/bmlt-workflow/files/12719847/error.log)
Sorry for your family.

**Comment by nigel-bmlt** [comment]
have identified the issue - it is a javascript bug due to multiple scripts colliding on the same page. I have addressed this in the code and will be pushing a new release 1.1.9 shortly to fix this. Please update when you see v1.1.9 available.

**Comment by Klodd65** [comment]
Nice job! Long live to worflow! THank you!
