### ISSUE TITLE
Filter Submissions View

### ISSUE THREAD

**Issue by tempsaint** [bmlt-enabled/bmlt-workflow#97]
This is a feature suggestion to build into the Workflow Submissions screen some filtering options. I think a great way would be to maybe have tabs... and have a Pending tab, an Approved tab, and a Rejected tab. The Approved and Rejected tabs would not need the Approve/Reject/Quick Edit buttons.  But I also see the Delete button there... so are you expecting admins to delete the submissions at some point? We think we would leave them indefinitely for tracking purposes.

**Comment by nigel-bmlt** [comment]
I originally implemented delete because I wanted to trash testing submissions rather than reject them all.

In 1.0.7 I have implemented a change to make delete available to wordpress admins only. Let me know if this would do the trick?

Tabs could definitely be an option. If it helps admins get through their jobs easier, I'm all for it.

![image](https://user-images.githubusercontent.com/99465040/193396062-2cb11aaa-c33d-4410-9d69-c470d53ac43e.png)

**Comment by tempsaint** [comment]
So, in practice, we expect service bodies to NOT delete the submissions? If so, then yes, we really a way to sort/filter the submissions (even if just separating Pending from Resolved - which would be both approved or rejected - but at that point I think having Pending, Approved, and Rejected filters would be better).  

It doesn't matter to me who can delete submissions. That's up to the service bodies to decide. And I think that's a separate issue from this issue that I submitted. I foresee years down the road... hundreds of meeting submissions in the Workflow Submissions screen, and a need to see all of the Approved submissions. As I type this, I'm wondering if a way to search the submissions is needed?

**Comment by nigel-bmlt** [comment]
Filter and search implemented in 1.0.20

![image](https://user-images.githubusercontent.com/99465040/216754498-2a865498-2e01-4f97-91e9-2a210fb46235.png)
